[package]
name = "invitation_record"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "../../frameworks/move-stdlib" }
MoveosStdlib = { local = "../../frameworks/moveos-stdlib" }
RoochFramework = { local = "../../frameworks/rooch-framework" }
app_admin = { local = "../../apps/app_admin" }
gas_faucet = {local = "../../apps/gas_faucet"}
twitter_binding = {local = "../../apps/twitter_binding"}

[addresses]
invitation_record = "_"
gas_faucet = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
app_admin = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
twitter_binding = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
